require: rubocop-rspec
inherit_from:
  - .rubocop-pernix.yml
Style/Documentation:
  Exclude:
    - "app/controllers/**/*"
    - "app/decorators/**/*"
    - "app/helpers/**/*"
    - "app/mailers/**/*"
    - "app/models/**/*"
    - "app/serializers/**/*"
    - "app/policies/**/*"
    - "app/validators/**/*"
    - "db/**/*"
    - "spec/**/*"
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"
Style/NumericLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Max: 40
  Exclude:
    # These are naturally DSL-y, and so let's be lenient.
    - "spec/**/*"
    - "config/routes.rb"
    - "app/admin/**/*"
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
